accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

groups/urls.py
from django.conf.urls import urls
from . import views


app_name = 'groups'

urlpatterns = [

url(r'^$', views.ListGroup.as_view(), name='list_group'),
url(r'^crete/$', views.CreateGroup.as_view(), name='create'),
url(r'^posts/in/(P?<slug>[-\w]+)/$', views.SingleGroup.as_view(), name='single')

]

posts/urls.py
from django.conf.urls import urls
from . import views

app_name = 'posts'

urlpatterns =[

    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)', views.UserPosts.as_view(), name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single')
    url(r'^(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete')
]

simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]

accounts/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone


class User(auth.models.User, auth.models.PermissionsMixin):
    
    def __str__(self):
        return "@{}".format(self.username)

groups/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.text import slugify
# from accounts.models import User

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()



class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships")
    user = models.ForeignKey(User,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

posts/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

import misaka

from groups.models import  Group

from django.contrib.auth import get_user_model
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts")
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

posts/forms.py
from django import forms

from posts import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

groups/views.py
from djano import render

from django.contrib.auth.mixin impoert(LoginRequiredMixinx, PermissionsMixins)
from django.views import generic

from django.models import Group,MemberGroup
from django.urls import reverse


class CreateGroup(LoginRequiredMixinx, generic.CreteView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

posts/views.py
from django.contrib.auth.mixin import LoginRequiredMixinx
from django.url import reverse_lazy
from django.views import generic
from braces.views import SelectRelatedMixin
from django.http import Http404

from . import models
from . import forms

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin,generic.ListView):

    model = models.Post
    select_related = ('user','group')

class UserPosts(generic.ListView):

    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post.user = User.objects.prefetch_related('post').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):

    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixinx,SelectRelatedMixin,generic.CreteView):

    model = models.Post
    fields = ('message','group')

    def form_valid(self):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixinx,SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user','group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        self.queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs) 

simplesocial/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse("test"))
        return super().get(request, *args, **kwargs)

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% bock content %}

<div class="conatiner">

  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block post_group %}{% endblock %}
  </div>

</div>


{% endblock%}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}

<h1>{{group.name}}</h1>
<h2>Number of Users:{{group.member.count}}</h2>

<div class="conatiner">

  {% if user in group.member.all %}
    <a href="{% url 'group:leave'%} slug=group.slug" class="btn btn-primary">
      <span class="glyphicon glyphicon-remove-circle">Leave</span>
    </a>

  {% else %}
    <a href="{% url 'group:join'%}" class="btn btn-danger">
      <span class="glyphicon glyphicon-ok-circle">Join</span>
    </a>
  {% endif %}
</div>

{% endblock %}

{% block groupcontent %}

<div class="col-md-8">
  {% if group.posts.count==0 %}
    <h1>NO post is Availbel in this group!!</h1>
  {% else %}

    {% for post in goup.post.all %}
      {% inlcude 'posts/_post.html' %}
    {% endfor %}

  {% endif %}
</div>


{% endblock %}

groups/templates/groups/group_form.html
{% extends 'group_base.html'%}

{% block content %}

<div class="container">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary"  value="Create">
  </form>

</div>

{% endblock %}

groups/templates/groups/group_list.html
{% extends 'gorups/group_base.html '%}

{% block pregroup %}

<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
      <h2>Welcome !!<a href="{% url 'posts:for_user' username=user.username }">
      @{{user.username}}</a></h2>

    {% endif %}

    <h2>Groups</h2>
    <p>Welocme To the group Page!!</p>
  </div>
  {% if user.is_authenticated %}
    <a href="{% url 'groups:create'%}" class="btn btn-primary ">
    <span class="glyphicon glyphicon-plus-sign">Create Group</span></a>
  {% endif %}
</div>

{% endblock %}

{% block group_content %}

<div class="col-md-8">
  <div class="list-group">
    {% for group in object_list %}
    <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item">
    <h3 class="title list-group-item-heading">{{group.name}}</h3>

    <div class="list-group-item-text container-fluid">
      {{group.description_html|safe}}
      <div class="row">
        <div class="col-md-4">
          <span class="badge">{{group.members.count}}</span>
          Member{{group.member.count|pluralize}}
        </div>
        <div class="col-md-4">
          <span class="badge">{{group.posts.count}}</span>
          post{{group.posts.count|pluralize}}

        </div>
      </div>
    </div>
  </a>
{% endfor %}

  </div>
</div>
{% endblock%}

posts/templates/posts/_post.html
<div class="post media">
	<h3>{{post.message_html|safe}}</h3>

	<div class="media-body">
		<strong>{{post.user.username}}</strong>
		<h5 class="media-heading">
		<span class="username">
			<a href="{% url 'posts:for-user' username=post.user.username%}"></a>
		</span>
		<time class="time">
			<a href="{% url 'posts:single' username=post.user.username pk=post.pk%}"></a>
		</time>
		</h5>

		<div class="media-footer">
			{% if user.is_authenticated and post.user==user %}
				<a href="{% url 'posts:delete' pk=post.pk%}" title="delete" class='btn btn-primary'>
					<span class="glyphicon glyphicon-remove text-danger" area-hiddn="true"></span>
					<span class="text-danger icon-lable">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}
{% block content %}

<div class="post-page">

	<div class="conatiner">
		<div class="row">
			{% block prepost %} {% endblock %}
			{% block post_content %} {% endblock %}
			{% bloc post_post %} {% endblock %}

		</div>

	</div>
</div>


{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}


{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="col-md-8">
    {% include "posts/_post.html" %}
</div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootsrtrap3 %}

{% block post_content %}
<h3>Crete A New Post!!</h3>

<form action="{% url 'posts:create'%}" method="post">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" class="btn btn-success" value="Post">
</form>

{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts:post_base.html" %}

{% block pre-post %}

<div class="col-md-4">
	{% if user.is_authenticated %}
		<div class="card card-eith-shadow">
			<div class="content">
				<h4>your groups!!</h4>
				<ul class="list-unstyled">
					{% for member_group in get_user_groups %}
					<li class="group li-with-bullet">
						<a href="{% url 'posts:single' slug=member_group.group.slug %}"></a>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	{% endif %}

	<div class="card card-with-shadow">
		<div class="content">
			<h4>All groups</h4>
			<ul class="list-unstyled">
				{% for other_gorup in grt_ohter_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=other_group_slug %}"></a>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>

{% endblock %}

{% block post_content %}

<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>


{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title> New SImple Star Social</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                      <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>
    <h2>The best community for all things on outer space!</h2>
    <h2>Login or Sign-up for free to get started!</h2>


{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>


</div>




{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}